#!/usr/bin/env bash

__version() {
  echo -e "\n${txtbld}deliver v$VERSION${txtrst} | $HOMEPAGE\n"
}

__help() {
  __version

  echo -e "${txtbld}USAGE${txtrst}
  ${txtcyn}deliver [COMMAND]${txtrst} ${txtylw}[MODE]${txtrst}

${txtbld}COMMANDS${txtrst}
  ${txtcyn}deliver help${txtrst}          This help message
  ${txtcyn}deliver version${txtrst}       Current deliver version
  ${txtcyn}deliver strategies${txtrst}    Lists all available strategies
  ${txtcyn}deliver check${txtrst}         Displays the entire configuration (highlights errors)
  ${txtcyn}deliver${txtrst}               Takes your code into production

${txtbld}MODES${txtrst}
  Each of the above commands supports the following runtime modes:

  ${txtylw}-C${txtrst}, ${txtylw}--compact${txtrst}   Displays progress, silences output. (default mode)
  ${txtylw}-P${txtrst}, ${txtylw}--plain${txtrst}     Same as compact, but has no colouring (CI friendly)
  ${txtylw}-V${txtrst}, ${txtylw}--verbose${txtrst}   Same as compact, does not silence output.
  ${txtylw}-D${txtrst}, ${txtylw}--debug${txtrst}     Shell debug mode.

${txtbld}MISCELLANEOUS:${txtrst}
  You can overwrite any config at runtime. Run ${txtcyn}deliver check${txtrst} to confirm this:

  HOSTS=ruby-1-local PORT=6000 ${txtcyn}deliver check${txtrst}
"
}

__available_strategies() {
  __version

  echo -e "${txtbld}STRATEGIES${txtrst}"

  for strategy in $STRATEGIES_NAME
  do
    echo "  ${txtmgt}$strategy${txtrst}"
  done

  echo ""
}

while (( $# ))
do
  arg="$1" && shift
  case "${arg}" in
    (-h|--help|help)
      __help
      exit 0
    ;;
    (-v|--version|version)
      __version
      exit 0
    ;;
    (-s|--strategies|strategies)
      __available_strategies
      exit 0
    ;;
    (-c|--check|check)
      CHECK=true
    ;;
    (-C|--compact)
      MODE="compact"
    ;;
    (-D|--debug)
      MODE="debug"
    ;;
    (-V|--verbose)
      MODE="verbose"
    ;;
    (-P|--plain)
      MODE="plain"
    ;;
    (*)
      hint_message "Unknown argument ${arg} ignored"
    ;;
  esac
done

case "${MODE}" in
  (compact)
    VERBOSE=""
    SILENCE="&> /dev/null"
  ;;
  (verbose)
    VERBOSE=true
    SILENCE=""
  ;;
  (debug)
    set -x
    VERBOSE=true
    SILENCE=""
  ;;
esac
